name: Python application test with Github Actions

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
       matrix:
         python-version: [3.8, 3.9, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Print Python version
      run: python --version

    - name: Run changed Python files and save output
      run: |
        echo "Python Version: ${{ matrix.python-version }}" > output.txt
        python --version >> output.txt
        CHANGED_FILES=$(git diff --name-only HEAD HEAD~1)
        for FILE in $CHANGED_FILES
        do
          if [[ $FILE == *.py ]]
          then
            echo "Running $FILE" >> output.txt
            python $FILE >> output.txt
          fi
        done

    - name: Upload output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-python${{ matrix.python-version }}
        path: output.txt
