name: Python Version Output

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Print Python version
      run: python --version

    - name: Save output to file
      run: |
        echo "Python ${{ matrix.python-version }}: $(python --version)" >> output.txt
      env:
        MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output.txt

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
